return {
  s("LEETCODE", {
    t({
      "from functools import *",
      "from bisect import *",
      "from collections import *",
      "from functools import *",
      "from heapq import *",
      "from itertools import *",
      "from math import *",
      "from random import *",
      "from re import *",
      "from typing import *",
      "",
      "from sortedcontainers import *",
      "",
      "",
      "class ListNode:",
      "    def __init__(self, val=0, next=None):",
      "        self.val = val",
      "        self.next = next",
      "",
      "",
      "class TreeNode:",
      "    def __init__(self, val=0, left=None, right=None):",
      "        self.val = val",
      "        self.left = left",
      "        self.right = right",
      "",
      "# from sortedcontainers import *",
      "",
      "",
      "",
    })
  })
}
